'use strict';

import { createHash } from 'crypto';

import { stableManagedValue } from './causal';
import { materializeManagedRemoteCatalog } from './merge';
import { ManagedRevisionSlot } from './types';

export interface ManagedSshProjectionEntry {
    machineId: string;
    alias: string;
    name: string;
    host: string;
    user: string;
    port: number;
}

export interface ManagedSshProjection {
    revisionId: string;
    connectionDigest: string;
    entries: ManagedSshProjectionEntry[];
    unavailableMachineIds: string[];
}

const SAFE_ALIAS = /^[\p{L}\p{N}][\p{L}\p{N}.-]{0,62}$/u;

function hash(value: string): string {
    return createHash('sha256').update(value, 'utf8').digest('hex');
}

function readableAliasSegment(value: string): string {
    const normalized = (value || '')
        .normalize('NFKC')
        .toLocaleLowerCase('en-US')
        .replace(/[^\p{L}\p{N}.]+/gu, '-')
        .replace(/^[.-]+|[.-]+$/gu, '');
    return Array.from(normalized).slice(0, 54).join('').replace(/[.-]+$/gu, '');
}

export function managedSshAliasName(machineName: string, connectionHost: string = ''): string {
    return readableAliasSegment(machineName)
        || readableAliasSegment(connectionHost)
        || 'machine';
}

export function managedSshAlias(
    _machineId: string,
    machineName: string = 'machine',
    connectionHost: string = '',
): string {
    const alias = managedSshAliasName(machineName, connectionHost);
    if (!SAFE_ALIAS.test(alias)) {
        throw new Error('Managed SSH alias generation failed.');
    }
    return alias;
}

export function isManagedSshAliasForMachine(
    alias: string,
    machineId: string,
    machineName: string = '',
    connectionHost: string = '',
): boolean {
    if (!SAFE_ALIAS.test(alias)) { return false; }
    const digest = hash(machineId);
    return alias === managedSshAlias(machineId, machineName, connectionHost)
        || alias === `agent-pivot-${digest.slice(0, 32)}`
        || alias.endsWith(`-${digest.slice(0, 8)}`);
}

export function buildManagedSshProjection(slot: ManagedRevisionSlot): ManagedSshProjection {
    const view = materializeManagedRemoteCatalog(slot.document);
    const unavailable = new Set(view.conflicts
        .filter(conflict => conflict.entityType === 'machine')
        .map(conflict => conflict.entityId));
    const entries = view.machines
        .filter(machine => !unavailable.has(machine.id))
        .map(machine => ({
            machineId: machine.id,
            alias: managedSshAlias(machine.id, machine.name, machine.connection.host),
            name: machine.name,
            host: machine.connection.host,
            user: machine.connection.user,
            port: machine.connection.port,
        }))
        .sort((left, right) => left.machineId.localeCompare(right.machineId));
    if (new Set(entries.map(entry => entry.alias.toLocaleLowerCase('en-US'))).size
        !== entries.length) {
        throw new Error('Managed Machine names must produce unique SSH aliases.');
    }
    const connectionDigest = hash(stableManagedValue(entries.map(entry => ({
        machineId: entry.machineId,
        alias: entry.alias,
        host: entry.host,
        user: entry.user,
        port: entry.port,
    }))));
    return {
        revisionId: slot.revisionId,
        connectionDigest,
        entries,
        unavailableMachineIds: Array.from(unavailable).sort(),
    };
}

export function renderManagedSshConfig(projection: ManagedSshProjection): string {
    const lines = [
        '# Generated by Agent Pivot. Do not edit.',
        `# Connection digest: ${projection.connectionDigest}`,
    ];
    for (const entry of projection.entries) {
        lines.push(
            '',
            `Host ${entry.alias}`,
            `    HostName ${entry.host}`,
            `    User ${entry.user}`,
            `    Port ${entry.port}`,
            '    ProxyJump none',
            '    ProxyCommand none',
            '    PermitLocalCommand no',
            '    ForwardAgent no',
            '    ForwardX11 no',
            '    RemoteCommand none',
            '    ControlMaster no',
        );
    }
    return `${lines.join('\n')}\n`;
}

export function renderManagedSshIncludeBlock(generatedConfigPath: string): string {
    if (!generatedConfigPath
        || /[\r\n\0"]/u.test(generatedConfigPath)) {
        throw new Error('Managed SSH config path cannot be represented safely.');
    }
    const sshConfigPath = generatedConfigPath.replace(/\\/gu, '/');
    return [
        '# >>> Agent Pivot managed SSH hosts (do not edit)',
        `Include "${sshConfigPath}"`,
        '# <<< Agent Pivot managed SSH hosts',
    ].join('\n');
}
