'use strict';

import { createHash } from 'crypto';

import { stableManagedValue } from './causal';
import { materializeManagedRemoteCatalog } from './merge';
import { ManagedRevisionSlot } from './types';

export interface ManagedSshProjectionEntry {
    machineId: string;
    alias: string;
    name: string;
    host: string;
    user: string;
    port: number;
    proxyJump?: string;
    sshConfigAlias?: string;
}

export interface ManagedSshProjection {
    revisionId: string;
    connectionDigest: string;
    entries: ManagedSshProjectionEntry[];
    unavailableMachineIds: string[];
}

export { isManagedSshAlias, managedSshAliasName, managedSshAliasSuffix,
    managedSshAlias, isManagedSshAliasForMachine, machineSshAlias } from './sshAlias';
import { machineSshAlias } from './sshAlias';

function hash(value: string): string {
    return createHash('sha256').update(value, 'utf8').digest('hex');
}

export function buildManagedSshProjection(slot: ManagedRevisionSlot): ManagedSshProjection {
    const view = materializeManagedRemoteCatalog(slot.document);
    const unavailable = new Set(view.conflicts
        .filter(conflict => conflict.entityType === 'machine')
        .map(conflict => conflict.entityId));
    const entries = view.machines
        .filter(machine => !unavailable.has(machine.id))
        .map(machine => ({
            machineId: machine.id,
            alias: machineSshAlias(machine),
            name: machine.name,
            host: machine.connection.host,
            user: machine.connection.user,
            port: machine.connection.port,
            ...(machine.connection.proxyJump ? { proxyJump: machine.connection.proxyJump } : {}),
            ...(machine.connection.sshConfigAlias ? { sshConfigAlias: machine.connection.sshConfigAlias } : {}),
        }))
        .sort((left, right) => left.machineId.localeCompare(right.machineId));
    if (new Set(entries.map(entry => entry.alias.toLocaleLowerCase('en-US'))).size
        !== entries.length) {
        throw new Error('Managed Machine names must produce unique SSH aliases.');
    }
    const connectionDigest = hash(stableManagedValue(entries.map(entry => ({
        machineId: entry.machineId,
        alias: entry.alias,
        host: entry.host,
        user: entry.user,
        port: entry.port,
        ...(entry.proxyJump ? { proxyJump: entry.proxyJump } : {}),
        ...(entry.sshConfigAlias ? { sshConfigAlias: entry.sshConfigAlias } : {}),
    }))));
    return {
        revisionId: slot.revisionId,
        connectionDigest,
        entries,
        unavailableMachineIds: Array.from(unavailable).sort(),
    };
}

export function renderManagedSshConfig(projection: ManagedSshProjection): string {
    const lines = [
        '# Generated by Agent Pivot. Do not edit.',
        `# Connection digest: ${projection.connectionDigest}`,
    ];
    for (const entry of projection.entries) {
        // Referenced hosts stay entirely owned by the user. Never shadow their directives.
        if (entry.sshConfigAlias) { continue; }
        lines.push(
            '',
            `Host ${entry.alias}`,
            `    HostName ${entry.host}`,
            `    User ${entry.user}`,
            `    Port ${entry.port}`,
            `    ProxyJump ${entry.proxyJump || 'none'}`,
            '    ProxyCommand none',
            '    PermitLocalCommand no',
            '    ForwardAgent no',
            '    ForwardX11 no',
            '    RemoteCommand none',
            '    ControlMaster no',
        );
    }
    return `${lines.join('\n')}\n`;
}

export function renderManagedSshIncludeBlock(generatedConfigPath: string): string {
    if (!generatedConfigPath
        || /[\r\n\0"]/u.test(generatedConfigPath)) {
        throw new Error('Managed SSH config path cannot be represented safely.');
    }
    const sshConfigPath = generatedConfigPath.replace(/\\/gu, '/');
    return [
        '# >>> Agent Pivot managed SSH hosts (do not edit)',
        `Include "${sshConfigPath}"`,
        '# <<< Agent Pivot managed SSH hosts',
    ].join('\n');
}
