'use strict';

const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');
const sharp = require('sharp');
const {
    renderSvg,
    updateAsset,
    validateSvgSource,
} = require('../../../scripts/generate-brand-assets');

const repositoryRoot = path.resolve(__dirname, '../../..');
const marketplaceSources = [
    'media/brand/agent-pivot-marketplace.svg',
    'media/brand/agent-pivot-bridge-marketplace.svg',
];
const allSvgSources = [...marketplaceSources, 'media/icon.svg'];
const approvedColors = new Set(['#111924', '#69dfd0', '#d8fff9']);

function readRepositoryFile(relativePath, encoding) {
    return fs.readFileSync(path.join(repositoryRoot, relativePath), encoding);
}

test('reviewed SVG sources contain only safe approved content', () => {
    for (const relativePath of allSvgSources) {
        const source = readRepositoryFile(relativePath, 'utf8');
        assert.doesNotThrow(() => validateSvgSource(source, relativePath));
    }

    for (const relativePath of marketplaceSources) {
        const source = readRepositoryFile(relativePath, 'utf8');
        const colors = new Set((source.match(/#[0-9a-f]{6}/gi) || [])
            .map(color => color.toLowerCase()));
        assert.deepEqual(colors, approvedColors, relativePath);
    }

    const activityBarSource = readRepositoryFile('media/icon.svg', 'utf8');
    assert.match(activityBarSource, /currentColor/);
    assert.equal(/#[0-9a-f]{3,8}/i.test(activityBarSource), false);
});

test('generated PNG assets are distinct 256px RGBA marketplace icons', async () => {
    const mainPng = readRepositoryFile('media/extension_icon.png');
    const bridgePng = readRepositoryFile(
        'extensions/attention-ui-bridge/media/extension_icon.png'
    );

    for (const png of [mainPng, bridgePng]) {
        const metadata = await sharp(png).metadata();
        assert.deepEqual(
            { width: metadata.width, height: metadata.height, format: metadata.format },
            { width: 256, height: 256, format: 'png' }
        );
    }

    const pixels = await sharp(mainPng).ensureAlpha().raw().toBuffer();
    const colors = new Set();
    for (let offset = 0; offset < pixels.length; offset += 4) {
        colors.add(pixels.subarray(offset, offset + 4).toString('hex'));
    }
    assert.ok(colors.has('111924ff'));
    assert.ok(colors.has('69dfd0ff'));
    assert.ok(colors.has('d8fff9ff'));
    assert.notDeepEqual(mainPng, bridgePng);
});

test('brand asset CLI confirms checked-in generated bytes are current', () => {
    const result = spawnSync(process.execPath, ['scripts/generate-brand-assets.js', '--check'], {
        cwd: repositoryRoot,
        encoding: 'utf8',
    });
    assert.equal(result.status, 0, result.stderr || result.stdout);
    assert.match(result.stdout, /Brand assets are current\./);
});

test('SVG validation rejects external or active content', () => {
    assert.throws(
        () => validateSvgSource(
            '<svg xmlns="http://www.w3.org/2000/svg"><image href="https://x"/></svg>',
            'hostile.svg'
        ),
        /external or active SVG content/
    );
});

test('SVG validation rejects spaced external references and mixed-case event attributes', () => {
    for (const [label, source] of [
        ['spaced-href.svg', '<svg href = "https://example.invalid/x"/>'],
        ['spaced-xlink.svg', '<svg xlink:href = "https://example.invalid/x"/>'],
        ['onload.svg', '<svg onload="alert(1)"/>'],
        ['mixed-case-event.svg', '<svg OnLoAd = "alert(1)"/>'],
    ]) {
        assert.throws(
            () => validateSvgSource(source, label),
            /external or active SVG content/
        );
    }
});

test('SVG validation rejects active SVG animation elements', () => {
    for (const [label, source] of [
        ['animate.svg', '<svg><animate attributeName="x"/></svg>'],
        ['set.svg', '<svg><set attributeName="x"/></svg>'],
        ['animate-motion.svg', '<svg><animateMotion/></svg>'],
        ['mixed-case-transform.svg', '<svg><AnimateTransform/></svg>'],
        ['mixed-case-discard.svg', '<svg><DISCARD/></svg>'],
    ]) {
        assert.throws(
            () => validateSvgSource(source, label),
            /external or active SVG content/
        );
    }
});

test('rasterizer failure preserves the last-known-good output', async () => {
    const safeMarketplaceSvg = readRepositoryFile(
        'media/brand/agent-pivot-marketplace.svg', 'utf8'
    );
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-pivot-asset-'));
    const inputPath = path.join(root, 'input.svg');
    const outputPath = path.join(root, 'output.png');
    fs.writeFileSync(inputPath, safeMarketplaceSvg);
    fs.writeFileSync(outputPath, Buffer.from('last-known-good'));

    await assert.rejects(
        updateAsset({
            inputPath,
            outputPath,
            check: false,
            rasterizer: () => { throw new Error('rasterizer unavailable'); },
            fsApi: fs,
        }),
        /rasterizer unavailable/
    );
    assert.deepEqual(fs.readFileSync(outputPath), Buffer.from('last-known-good'));
});

test('rename failure preserves the output and removes the temporary file', async () => {
    const safeMarketplaceSvg = readRepositoryFile(
        'media/brand/agent-pivot-marketplace.svg', 'utf8'
    );
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-pivot-asset-'));
    const inputPath = path.join(root, 'input.svg');
    const outputPath = path.join(root, 'output.png');
    const temporaryPath = `${outputPath}.tmp`;
    fs.writeFileSync(inputPath, safeMarketplaceSvg);
    fs.writeFileSync(outputPath, Buffer.from('last-known-good'));

    const fsApi = Object.assign({}, fs, {
        renameSync() {
            throw new Error('write cannot complete');
        },
    });

    await assert.rejects(
        updateAsset({ inputPath, outputPath, check: false, rasterizer: sharp, fsApi }),
        /write cannot complete/
    );
    assert.deepEqual(fs.readFileSync(outputPath), Buffer.from('last-known-good'));
    assert.equal(fs.existsSync(temporaryPath), false);
});

test('check mode reports stale bytes in an isolated fixture', () => {
    const fixtureRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-pivot-check-'));
    const fixtureMainIcon = path.join(fixtureRoot, 'media/extension_icon.png');
    const fixtureBridgeIcon = path.join(
        fixtureRoot, 'extensions/attention-ui-bridge/media/extension_icon.png'
    );
    for (const relativePath of marketplaceSources) {
        const destination = path.join(fixtureRoot, relativePath);
        fs.mkdirSync(path.dirname(destination), { recursive: true });
        fs.copyFileSync(path.join(repositoryRoot, relativePath), destination);
    }
    for (const [source, destination] of [
        ['media/extension_icon.png', fixtureMainIcon],
        ['extensions/attention-ui-bridge/media/extension_icon.png', fixtureBridgeIcon],
    ]) {
        fs.mkdirSync(path.dirname(destination), { recursive: true });
        fs.copyFileSync(path.join(repositoryRoot, source), destination);
    }

    const bytes = fs.readFileSync(fixtureMainIcon);
    bytes[bytes.length - 1] ^= 0xff;
    fs.writeFileSync(fixtureMainIcon, bytes);

    const result = spawnSync(process.execPath, [
        path.join(repositoryRoot, 'scripts/generate-brand-assets.js'), '--check',
    ], { cwd: fixtureRoot, encoding: 'utf8' });
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /media\/extension_icon\.png is stale/);
});

test('renderSvg creates a deterministic 256px RGBA PNG', async () => {
    const source = readRepositoryFile('media/brand/agent-pivot-marketplace.svg', 'utf8');
    const rendered = await renderSvg(source);
    const metadata = await sharp(rendered).metadata();
    assert.deepEqual(
        {
            format: metadata.format,
            width: metadata.width,
            height: metadata.height,
            channels: metadata.channels,
        },
        { format: 'png', width: 256, height: 256, channels: 4 }
    );
});
